"""empty message

Revision ID: 356c2f1c7b98
Revises: 0a7b29d2c04e
Create Date: 2021-05-23 18:15:03.815524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356c2f1c7b98'
down_revision = '0a7b29d2c04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
